# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Stage 1 - Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo Executando o stage de Build
  - stage: Desenv
    dependsOn: [ Build ]
    displayName:  Stage 2 - Desenv
    jobs:
      - job: Desenv
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo Executando o stage de Desenv
  - stage: Homolog
    dependsOn: [ Desenv ]
    displayName:  Stage 3 - Homolog
    jobs:
      - job: Homolog
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo Executando o stage de Homologação
  - stage: Testes
    dependsOn: [ Desenv ]
    displayName:  Stage 5 - Testes
    jobs:
      - job: Testes
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo Executando o stage de Testes
  - stage: Prod
    dependsOn: 
      - Homolog
      - Testes
    displayName:  Stage 4 - Produção
    jobs:
      - job: Prod
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo Executando o stage de Produção